version: '3.7'
services:
  database:
    image: mongo:latest
    container_name: database
    restart: always
    command: [--auth]
    environment:
      MONGO_INITDB_ROOT_USERNAME: "$MONGO_INITDB_ROOT_USERNAME"
      MONGO_INITDB_ROOT_PASSWORD: "$MONGO_INITDB_ROOT_PASSWORD"
      DB_NAME: "$DB_NAME"
      DB_USER: "$DB_USER"
      DB_PASS: "$DB_PASS"
      DB_HOST: "$DB_HOST"
      DB_PORT: "$DB_PORT"
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
  data-seed:
    image: mongo:latest
    container_name: data-seed
    build:
      context: ../data
      dockerfile: Dockerfile
    links:
      - database:mongo
    env_file: .env
    environment:
      DB_NAME: "$DB_NAME"
      DB_USER: "$DB_USER"
      DB_PASS: "$DB_PASS"
      DB_HOST: "$DB_HOST"
  api:
    build:
      context: ../api
      dockerfile: Dockerfile
    volumes:
      - ../api/src/:/home/node/api/src
    links:
      - database:mongo
    depends_on:
      - database
    env_file: .env
    environment:
        NODE_ENV: development
        DB_NAME: "$DB_NAME"
        DB_USER: "$DB_USER"
        DB_PASS: "$DB_PASS"
        DB_HOST: "$DB_HOST"
        DB_PORT: "$DB_PORT"
        JWT_SECRET: "$JWT_SECRET"
        WAIT_HOSTS: database:27017
    ports:
        - 8080:8080
  app:
    stdin_open: true
    tty: true
    restart: always
    build:
      context: ../app
      dockerfile: Dockerfile
    volumes:
      - ../app/src/:/home/node/app/src
    environment:
        NODE_ENV: development
    ports:
      - 3000:3000

